image: "gcc:8.3.0"

before_script:
  - apt-get update -qq && apt-get install -y -qq glib2.0-dev python3-pip lcov
  - pip3 install pytest
  - wget -q https://github.com/Kitware/CMake/releases/download/v3.15.2/cmake-3.15.2-Linux-x86_64.tar.gz
  - tar -C /usr/local/ -xzf cmake-3.15.2-Linux-x86_64.tar.gz
  - rm cmake-3.15.2-Linux-x86_64.tar.gz
  - ln -s /usr/local/cmake-3.15.2-Linux-x86_64/bin/cmake /usr/local/bin
  - ln -s /usr/local/cmake-3.15.2-Linux-x86_64/bin/ctest /usr/local/bin

ctest:
    script:
      - mkdir cmake-build && cd cmake-build
      - cmake ..
      - make
      - ctest -VV
      - lcov --directory . --capture --output-file coverage.info
      - lcov --remove coverage.info '*/test/*' --output-file coverage.info
      - lcov --list coverage.info