dist: bionic
language: c
os: linux
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-8
env:
  - CC=gcc-8
compiler: gcc

install:
  - sudo apt-get update -qq && sudo apt-get install -y -qq glib2.0-dev python3-pip tree
  - pip3 install pytest
  - wget -q https://github.com/Kitware/CMake/releases/download/v3.15.2/cmake-3.15.2-Linux-x86_64.tar.gz
  - wget -q http://ftp.us.debian.org/debian/pool/main/l/lcov/lcov_1.13-4_all.deb
  - sudo apt-get install -y -f ./lcov_1.13-4_all.deb
  - sudo tar -C /usr/local/ -xzf cmake-3.15.2-Linux-x86_64.tar.gz
  - rm cmake-3.15.2-Linux-x86_64.tar.gz
  - export PATH=/usr/local/cmake-3.15.2-Linux-x86_64/bin/:$PATH
  - echo $PATH
  - sudo ln -s /usr/local/cmake-3.15.2-Linux-x86_64/bin/cmake /usr/local/bin
  - sudo ln -s /usr/local/cmake-3.15.2-Linux-x86_64/bin/ctest /usr/local/bin

script:
  - cmake --version
  - mkdir cmake-build && cd cmake-build
  - cmake ..
  - make
  - ctest -VV
  - lcov --version
  - lcov --gcov-tool $(which gcov-8) --directory . --capture --output-file coverage.info
  - lcov --gcov-tool $(which gcov-8) --remove coverage.info '*/test/*' --output-file coverage.info
  - lcov --gcov-tool $(which gcov-8) --list coverage.info
  - bash <(curl -s https://codecov.io/bash) -f coverage.info -t 98c23671-ce6d-47e6-90e8-f656ed878ea0