#ifndef CODES_H
#define CODES_H

#define ERR_NOSUCHNICK 401
#define ERR_NOSUCHSERVER 402
#define ERR_UNKNOWNCOMMAND 421
#define ERR_NONICKNAMEGIVEN 431
#define ERR_ERRONEUSNICKNAME 432
#define ERR_NEEDMOREPARAMS 461


#endif